using System.ComponentModel.DataAnnotations;
using FormaAI.Domain.Training;
using FormaAI.Domain.Progress;

namespace FormaAI.Contracts.Training;

public sealed record ExerciseMuscleEngagementResponse(MuscleGroup MuscleGroup, int Percentage);
public sealed record ExerciseMuscleEngagementRequest(MuscleGroup MuscleGroup, [Range(1, 100)] int Percentage);
public sealed record ExerciseResponse(Guid Id, string Name, MuscleGroup MuscleGroup, Equipment Equipment, bool IsUnilateral, bool IsOwn, string? Description = null, IReadOnlyList<ExerciseMuscleEngagementResponse>? MuscleEngagements = null);
public sealed record SaveExerciseRequest([Required, MaxLength(150)] string Name, MuscleGroup MuscleGroup, Equipment Equipment, bool IsUnilateral, [MaxLength(1000)] string? Description = null, IReadOnlyList<ExerciseMuscleEngagementRequest>? MuscleEngagements = null);
public sealed record PlannedExerciseRequest(Guid ExerciseId, [Range(1, 10)] int Sets, [Range(1, 100)] int MinReps, [Range(1, 100)] int MaxReps, [Range(0, 10)] decimal? TargetRir, [Range(0, 3600)] int? RestSeconds);
public sealed record TrainingDayRequest([Required, MaxLength(100)] string Name, DayOfWeek? DayOfWeek, [MinLength(1)] IReadOnlyList<PlannedExerciseRequest> Exercises);
public sealed record SaveTrainingPlanRequest([Required, MaxLength(150)] string Name, [MaxLength(500)] string Goal, DateOnly StartsOn, [MinLength(1)] IReadOnlyList<TrainingDayRequest> Days);
public sealed record PlannedExerciseResponse(Guid Id, Guid ExerciseId, string ExerciseName, int Sets, int MinReps, int MaxReps, decimal? TargetRir, int? RestSeconds);
public sealed record TrainingDayResponse(Guid Id, string Name, DayOfWeek? DayOfWeek, int SequenceNumber, IReadOnlyList<PlannedExerciseResponse> Exercises);
public sealed record TrainingPlanResponse(Guid Id, string Name, string Goal, bool IsActive, DateOnly StartsOn, IReadOnlyList<TrainingDayResponse> Days);
public sealed record TodayWorkoutResponse(Guid PlanId, Guid TrainingDayId, string PlanName, string DayName, bool AlreadyCompleted, IReadOnlyList<PlannedExerciseResponse> Exercises);
public sealed record StartWorkoutRequest(Guid TrainingDayId, int? TimeLimitMinutes = null);
public sealed record SaveSetRequest(Guid WorkoutExerciseId, [Range(1, 50)] int SetNumber, [Range(0, 1000)] decimal WeightKg, [Range(1, 1000)] int Repetitions, [Range(0, 10)] decimal? Rir, SetType SetType, [MaxLength(300)] string? Notes = null);
public sealed record CompletedSetResponse(Guid Id, int SetNumber, decimal WeightKg, int Repetitions, decimal? Rir, SetType SetType, DateTime CompletedAtUtc, string? Notes = null);
public sealed record AddWorkoutExerciseRequest(Guid ExerciseId, [Range(1, 10)] int PlannedSets = 3, [Range(1, 100)] int MinReps = 8, [Range(1, 100)] int MaxReps = 12, [Range(0, 10)] decimal? TargetRir = 2, [Range(0, 3600)] int? RestSeconds = 90);
public sealed record ReplaceWorkoutExerciseRequest(Guid ExerciseId);
public sealed record SaveWorkoutNotesRequest([MaxLength(1000)] string? Notes);
public sealed record WorkoutExerciseResponse(Guid Id, Guid? ExerciseId, string ExerciseName, int Order, int PlannedSets, int MinReps, int MaxReps, decimal? TargetRir, int? RestSeconds, IReadOnlyList<CompletedSetResponse> Sets);
public sealed record WorkoutSessionResponse(Guid Id, string Name, DateTime StartedAtUtc, DateTime? FinishedAtUtc, SessionStatus Status, IReadOnlyList<WorkoutExerciseResponse> Exercises, bool IsShortened = false, int? TimeLimitMinutes = null);
public sealed record ExerciseHistoryEntry(DateTime CompletedAtUtc, decimal WeightKg, int Repetitions, decimal? Rir, decimal Volume);
public sealed record ExerciseProgressionResponse(Guid Id, Guid ExerciseId, string ExerciseName, decimal SuggestedWeightKg, int MinReps, int MaxReps, string Reason, ProgressionDecision Decision, decimal? AcceptedWeightKg);
public sealed record DecideProgressionRequest(ProgressionDecision Decision, [Range(0, 1000)] decimal? WeightKg = null);
public sealed record TrainingScheduleExceptionResponse(Guid Id, Guid TrainingDayId, string TrainingDayName, DateOnly OriginalDate, DateOnly? NewDate, ScheduleDecision Decision, string? Reason);
public sealed record SaveTrainingScheduleExceptionRequest(Guid TrainingDayId, DateOnly OriginalDate, DateOnly? NewDate, ScheduleDecision Decision, [MaxLength(500)] string? Reason = null);
